name: Docker Build & Push

on:
  workflow_run:
    workflows: ["CI Workflow Back", "CI Workflow Front"]
    types:
      - completed

concurrency:
  group: cd-back-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  build-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push' &&
        github.event.workflow_run.head_branch == 'main'
      }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend
      - name: Build & Push Backend
        run: |
          docker build -t yoricklio/bobapp-back:latest ./back
          docker push yoricklio/bobapp-back:latest

      # Frontend
      - name: Build & Push Frontend
        run: |
          docker build -t yoricklio/bobapp-front:latest ./front
          docker push yoricklio/bobapp-front:latest
