name: Docker Front/back Build & Push

on:
  push:
    branches: [ main ]

concurrency:
  group: cd-main
  cancel-in-progress: true

jobs:
  build-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: |
            yoricklio/bobapp-back:${{ github.sha }}
            yoricklio/bobapp-back:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      # Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: |
            yoricklio/bobapp-front:${{ github.sha }}
            yoricklio/bobapp-front:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64